
package com.sig.view;

import com.sig.controller.FilesManager1;
import com.sig.modle.invoiceHeader;
import com.sig.modle.invoiceLine;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;


public class AddLine extends javax.swing.JFrame {

    /**
     * Creates new form AddInvoice
     */
    String filepathh;
    String filepathl;
    String id;
    public AddLine() {
        initComponents();
    }
    public AddLine(String filepathh,String filepathl,String id) {
        this.filepathh = filepathh;
        this.filepathl = filepathl;
        this.id = id;
      
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        CusName = new javax.swing.JTextField();
        Okbut = new javax.swing.JButton();
        CancBut = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InvDate1 = new javax.swing.JTextField();
        CusName1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Item Name");

        CusName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusNameActionPerformed(evt);
            }
        });

        Okbut.setText("OK");
        Okbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkbutActionPerformed(evt);
            }
        });

        CancBut.setText("Cancel");
        CancBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancButActionPerformed(evt);
            }
        });

        jLabel3.setText("Item Price");

        jLabel4.setText("Count");

        InvDate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvDate1ActionPerformed(evt);
            }
        });

        CusName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CusName1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Okbut)
                        .addGap(38, 38, 38)
                        .addComponent(CancBut)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InvDate1)
                            .addComponent(CusName1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CusName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InvDate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CusName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Okbut)
                    .addComponent(CancBut))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CusNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusNameActionPerformed

    private void OkbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkbutActionPerformed
        // TODO add your handling code here:
        ArrayList<invoiceLine> all3 = new ArrayList<>();
        invoiceLine i = new invoiceLine();
        i.setfilepath(filepathl);
        i.ReadFileinvoiceLines();
        all3 = i.getLines();
        i.setnumber(Integer.parseInt(id));
        try {
     i.setPrice(Float.parseFloat(InvDate1.getText()));

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cannot convert number", "Invalid number format", JOptionPane.ERROR_MESSAGE);
        }
        i.setItem(CusName.getText());
        
        try {
              i.setCount(Integer.parseInt(CusName1.getText()));
        }catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Cannot convert price", "Invalid number format", JOptionPane.ERROR_MESSAGE);
        }
      
        all3.add(i);
     System.out.println("the invoice id is "+ id + " invoice Name is " + CusName.getText()+" invoice price is "+ InvDate1.getText() + " invoice count is " + CusName1.getText());
        i.setLines(all3);
        i.WriteFileinvoiceLines();
        this.setVisible(false);
        
        InvoiceFram a = new InvoiceFram(filepathh,filepathl);
        a.setVisible(true);
       System.out.println("invoice is added");
          
    }//GEN-LAST:event_OkbutActionPerformed

    private void CancButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        InvoiceFram a = new InvoiceFram(filepathh,filepathl);
        a.setVisible(true);
    }//GEN-LAST:event_CancButActionPerformed

    private void InvDate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvDate1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvDate1ActionPerformed

    private void CusName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CusName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CusName1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddLine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddLine().setVisible(true);
            }  
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancBut;
    private javax.swing.JTextField CusName;
    private javax.swing.JTextField CusName1;
    private javax.swing.JTextField InvDate1;
    private javax.swing.JButton Okbut;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
